Fix: deal with stopped container

diff --git a/.bin/dev b/.bin/dev
--- a/.bin/dev
+++ b/.bin/dev
@@ -1,8 +1,8 @@
-#!/bin/bash
+##!/bin/bash
 set -e
 
 # show help
-if [[ $1 == "-h" ]]; then
+if [[ $1 == "-h" || "$#" -gt 1 ]]; then
 	echo -e "Usage:\n $0\n-r rebuild container\n-d set working dir to pwd"
 	exit 0
 fi
@@ -18,6 +18,7 @@ fi
 # check if network exists
 docker network inspect dev_net >/dev/null 2>&1
 if [[ $? != 0 ]]; then
+	set -e
 	docker network create dev_net --subnet=10.11.0.0/16
 fi
 set -e
@@ -31,6 +32,10 @@ fi
 
 # ensure container is running
 if [ ! "$(docker ps -q -f name=dev)" ]; then
+	if [ "$(docker ps -aq -f status=exited -f name=dev)" ]; then
+        # cleanup
+        docker rm dev
+    fi
     # run container
 	docker run -it -d --name dev -h dev --net dev_net --ip 10.11.0.10 -v /home/$USER/.ssh:/home/patrick/.ssh:ro -v /home/$USER:/host patrickhaussmann/dev
 fi
@@ -43,6 +48,4 @@ if [[ $1 == "-d" ]]; then
 	fi
 fi
 
-
 docker exec -it dev bash
-#docker attach --sig-proxy=false dev
